/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'targetRole' : IDL.Text,
});
export const SchoolEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const FeePayment = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'term' : IDL.Nat,
  'year' : IDL.Nat,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const FeeStructure = IDL.Record({
  'id' : IDL.Nat,
  'item' : IDL.Text,
  'term' : IDL.Nat,
  'year' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const CBCGrade = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'term' : IDL.Nat,
  'year' : IDL.Nat,
  'level' : IDL.Text,
  'score' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'teacherId' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'parentId' : IDL.Principal,
  'studentClass' : IDL.Text,
});
export const CBCSubject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'teacher' : IDL.Text,
});
export const SchoolRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'schoolRole' : SchoolRole,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createFeePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createFeeStructure' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createGrade' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteFeePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteFeeStructure' : IDL.Func([IDL.Nat], [], []),
  'deleteGrade' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(SchoolEvent)], ['query']),
  'getAllFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'getAllFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
  'getAllGrades' : IDL.Func([], [IDL.Vec(CBCGrade)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(CBCSubject)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [SchoolEvent], ['query']),
  'getFeeBalanceForStudent' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Int],
      ['query'],
    ),
  'getFeePayment' : IDL.Func([IDL.Nat], [FeePayment], ['query']),
  'getFeeStructure' : IDL.Func([IDL.Nat], [FeeStructure], ['query']),
  'getGrade' : IDL.Func([IDL.Nat], [CBCGrade], ['query']),
  'getGradesByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(CBCGrade)], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getSubject' : IDL.Func([IDL.Nat], [CBCSubject], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(SchoolEvent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateFeePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateFeeStructure' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateGrade' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'targetRole' : IDL.Text,
  });
  const SchoolEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const FeePayment = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'term' : IDL.Nat,
    'year' : IDL.Nat,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const FeeStructure = IDL.Record({
    'id' : IDL.Nat,
    'item' : IDL.Text,
    'term' : IDL.Nat,
    'year' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const CBCGrade = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'term' : IDL.Nat,
    'year' : IDL.Nat,
    'level' : IDL.Text,
    'score' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'teacherId' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'parentId' : IDL.Principal,
    'studentClass' : IDL.Text,
  });
  const CBCSubject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'teacher' : IDL.Text,
  });
  const SchoolRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'schoolRole' : SchoolRole,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createFeePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createFeeStructure' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createGrade' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteFeePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteFeeStructure' : IDL.Func([IDL.Nat], [], []),
    'deleteGrade' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(SchoolEvent)], ['query']),
    'getAllFeePayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'getAllFeeStructures' : IDL.Func([], [IDL.Vec(FeeStructure)], ['query']),
    'getAllGrades' : IDL.Func([], [IDL.Vec(CBCGrade)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(CBCSubject)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [SchoolEvent], ['query']),
    'getFeeBalanceForStudent' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Int],
        ['query'],
      ),
    'getFeePayment' : IDL.Func([IDL.Nat], [FeePayment], ['query']),
    'getFeeStructure' : IDL.Func([IDL.Nat], [FeeStructure], ['query']),
    'getGrade' : IDL.Func([IDL.Nat], [CBCGrade], ['query']),
    'getGradesByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(CBCGrade)], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getSubject' : IDL.Func([IDL.Nat], [CBCSubject], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(SchoolEvent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateFeePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateFeeStructure' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateGrade' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };