/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'targetRole' : string,
}
export interface CBCGrade {
  'id' : bigint,
  'studentId' : bigint,
  'term' : bigint,
  'year' : bigint,
  'level' : string,
  'score' : bigint,
  'subjectId' : bigint,
  'teacherId' : bigint,
  'remarks' : string,
}
export interface CBCSubject {
  'id' : bigint,
  'name' : string,
  'teacher' : string,
}
export interface FeePayment {
  'id' : bigint,
  'studentId' : bigint,
  'date' : string,
  'term' : bigint,
  'year' : bigint,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface FeeStructure {
  'id' : bigint,
  'item' : string,
  'term' : bigint,
  'year' : bigint,
  'amount' : bigint,
}
export interface SchoolEvent {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'description' : string,
  'category' : string,
}
export type SchoolRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export interface Student {
  'id' : bigint,
  'name' : string,
  'admissionNumber' : string,
  'parentId' : Principal,
  'studentClass' : string,
}
export interface UserProfile {
  'schoolRole' : SchoolRole,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string, string, string], bigint>,
  'createEvent' : ActorMethod<[string, string, string, string], bigint>,
  'createFeePayment' : ActorMethod<
    [bigint, bigint, string, string, bigint, bigint],
    bigint
  >,
  'createFeeStructure' : ActorMethod<[string, bigint, bigint, bigint], bigint>,
  'createGrade' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, bigint, string, bigint],
    bigint
  >,
  'createStudent' : ActorMethod<[string, string, string, Principal], bigint>,
  'createSubject' : ActorMethod<[string, string], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteFeePayment' : ActorMethod<[bigint], undefined>,
  'deleteFeeStructure' : ActorMethod<[bigint], undefined>,
  'deleteGrade' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllEvents' : ActorMethod<[], Array<SchoolEvent>>,
  'getAllFeePayments' : ActorMethod<[], Array<FeePayment>>,
  'getAllFeeStructures' : ActorMethod<[], Array<FeeStructure>>,
  'getAllGrades' : ActorMethod<[], Array<CBCGrade>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubjects' : ActorMethod<[], Array<CBCSubject>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], SchoolEvent>,
  'getFeeBalanceForStudent' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'getFeePayment' : ActorMethod<[bigint], FeePayment>,
  'getFeeStructure' : ActorMethod<[bigint], FeeStructure>,
  'getGrade' : ActorMethod<[bigint], CBCGrade>,
  'getGradesByStudent' : ActorMethod<[bigint], Array<CBCGrade>>,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getSubject' : ActorMethod<[bigint], CBCSubject>,
  'getUpcomingEvents' : ActorMethod<[], Array<SchoolEvent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateFeePayment' : ActorMethod<
    [bigint, bigint, bigint, string, string, bigint, bigint],
    undefined
  >,
  'updateFeeStructure' : ActorMethod<
    [bigint, string, bigint, bigint, bigint],
    undefined
  >,
  'updateGrade' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, string, bigint, string, bigint],
    undefined
  >,
  'updateStudent' : ActorMethod<
    [bigint, string, string, string, Principal],
    undefined
  >,
  'updateSubject' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];